server:
<<<<<<< HEAD
  port: ${PORT:7779}
  servlet:
    context-path: /api
=======
  port: ${PORT:7778}
>>>>>>> BTLLC-Feature-79/81/82/84
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: ${ACTPORT:0}
gateway:
  ip: ${GATEWAY:192.168.1.36}
spring:
  application:
<<<<<<< HEAD
    name: ${NAME:cards-service}
=======
    name: ${NAME:card-service}
>>>>>>> BTLLC-Feature-79/81/82/84
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: dev
    password: dev
    driver-class-name: org.h2.Driver
  jpa:
<<<<<<< HEAD
    database-platform: org.hibernate.dialect.H2Dialect
authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer
token:
  secret: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj04WnEzS0NCZWQ1UQo=
  expiration: 864000000
=======
    database-platform: org.hibernate.dialect.H2Dialect
>>>>>>> BTLLC-Feature-79/81/82/84
