server:
  port: ${PORT:7779}
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: ${ACTPORT:0}
gateway:
  ip: ${GATEWAY:localhost}
spring:
  application:
    name: ${NAME:cards-service}
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:mariadb://localhost:3306/BeardTrust
    username: beardtrust_dev
    password: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1KVm9jM1lmejFwawo=
    driver-class-name: org.mariadb.jdbc.Driver
